import { db } from '@/db';
import { quizQuestions } from '@/db/schema';

async function main() {
    const sampleQuestions = [
        {
            question: 'What is 5 + 3?',
            options: JSON.stringify(['6', '7', '8', '9']),
            correctAnswer: 2,
            explanation: 'When you add 5 and 3 together, you count 5 first, then count 3 more: 6, 7, 8. The answer is 8.',
            topic: 'Addition',
            difficulty: 'Beginner',
            createdAt: new Date().toISOString(),
        },
        {
            question: 'What is 12 + 7?',
            options: JSON.stringify(['17', '18', '19', '20']),
            correctAnswer: 2,
            explanation: 'Starting from 12, count forward 7 steps: 13, 14, 15, 16, 17, 18, 19. The answer is 19.',
            topic: 'Addition',
            difficulty: 'Beginner',
            createdAt: new Date().toISOString(),
        },
        {
            question: 'What is 10 - 4?',
            options: JSON.stringify(['4', '5', '6', '7']),
            correctAnswer: 2,
            explanation: 'Starting with 10, count backwards 4 steps: 9, 8, 7, 6. The answer is 6.',
            topic: 'Subtraction',
            difficulty: 'Beginner',
            createdAt: new Date().toISOString(),
        },
        {
            question: 'What is 25 - 8?',
            options: JSON.stringify(['15', '16', '17', '18']),
            correctAnswer: 2,
            explanation: 'From 25, subtract 8 by counting back: 24, 23, 22, 21, 20, 19, 18, 17. The answer is 17.',
            topic: 'Subtraction',
            difficulty: 'Beginner',
            createdAt: new Date().toISOString(),
        },
        {
            question: 'What is 6 × 4?',
            options: JSON.stringify(['20', '22', '24', '26']),
            correctAnswer: 2,
            explanation: 'Multiply 6 by 4 means adding 6 four times: 6 + 6 + 6 + 6 = 24. The answer is 24.',
            topic: 'Multiplication',
            difficulty: 'Beginner',
            createdAt: new Date().toISOString(),
        },
        {
            question: 'What is 9 × 7?',
            options: JSON.stringify(['56', '63', '72', '81']),
            correctAnswer: 1,
            explanation: '9 times 7 equals 63. You can think of it as 9 + 9 + 9 + 9 + 9 + 9 + 9 or use the multiplication table.',
            topic: 'Multiplication',
            difficulty: 'Intermediate',
            createdAt: new Date().toISOString(),
        },
        {
            question: 'What is 24 ÷ 6?',
            options: JSON.stringify(['3', '4', '5', '6']),
            correctAnswer: 1,
            explanation: 'Division asks how many groups of 6 fit into 24. Since 6 × 4 = 24, the answer is 4.',
            topic: 'Division',
            difficulty: 'Intermediate',
            createdAt: new Date().toISOString(),
        },
        {
            question: 'What is 56 ÷ 8?',
            options: JSON.stringify(['6', '7', '8', '9']),
            correctAnswer: 1,
            explanation: 'To find 56 ÷ 8, think about what times 8 equals 56. Since 8 × 7 = 56, the answer is 7.',
            topic: 'Division',
            difficulty: 'Intermediate',
            createdAt: new Date().toISOString(),
        },
        {
            question: 'What is 1/2 + 1/4?',
            options: JSON.stringify(['1/4', '2/6', '3/4', '1/6']),
            correctAnswer: 2,
            explanation: 'To add fractions, find a common denominator. 1/2 = 2/4, so 2/4 + 1/4 = 3/4.',
            topic: 'Fractions',
            difficulty: 'Intermediate',
            createdAt: new Date().toISOString(),
        },
        {
            question: 'What is 3/4 of 20?',
            options: JSON.stringify(['10', '12', '15', '18']),
            correctAnswer: 2,
            explanation: 'To find 3/4 of 20, divide 20 by 4 to get 5, then multiply by 3: 5 × 3 = 15.',
            topic: 'Fractions',
            difficulty: 'Intermediate',
            createdAt: new Date().toISOString(),
        },
        {
            question: 'What is 0.5 + 0.25?',
            options: JSON.stringify(['0.5', '0.65', '0.75', '0.85']),
            correctAnswer: 2,
            explanation: 'Add the decimal numbers: 0.5 + 0.25 = 0.75. You can think of it as 50 cents + 25 cents = 75 cents.',
            topic: 'Decimals',
            difficulty: 'Intermediate',
            createdAt: new Date().toISOString(),
        },
        {
            question: 'What is 2.5 × 4?',
            options: JSON.stringify(['8', '9', '10', '11']),
            correctAnswer: 2,
            explanation: 'Multiply 2.5 by 4: 2.5 × 4 = 10. Think of it as 2 × 4 = 8, plus 0.5 × 4 = 2, so 8 + 2 = 10.',
            topic: 'Decimals',
            difficulty: 'Intermediate',
            createdAt: new Date().toISOString(),
        },
        {
            question: 'What is 45 + 67?',
            options: JSON.stringify(['102', '110', '112', '122']),
            correctAnswer: 2,
            explanation: 'Add the ones place: 5 + 7 = 12 (write 2, carry 1). Add tens: 4 + 6 + 1 = 11. Answer is 112.',
            topic: 'Addition',
            difficulty: 'Intermediate',
            createdAt: new Date().toISOString(),
        },
        {
            question: 'What is 100 - 37?',
            options: JSON.stringify(['53', '63', '73', '83']),
            correctAnswer: 1,
            explanation: 'Subtract 37 from 100. Think: 100 - 30 = 70, then 70 - 7 = 63. The answer is 63.',
            topic: 'Subtraction',
            difficulty: 'Intermediate',
            createdAt: new Date().toISOString(),
        },
        {
            question: 'What is 12 × 8?',
            options: JSON.stringify(['84', '88', '92', '96']),
            correctAnswer: 3,
            explanation: '12 × 8 = 96. You can calculate this as (10 × 8) + (2 × 8) = 80 + 16 = 96.',
            topic: 'Multiplication',
            difficulty: 'Advanced',
            createdAt: new Date().toISOString(),
        },
        {
            question: 'What is 144 ÷ 12?',
            options: JSON.stringify(['10', '11', '12', '13']),
            correctAnswer: 2,
            explanation: '144 ÷ 12 = 12. This is asking how many 12s are in 144. Since 12 × 12 = 144, the answer is 12.',
            topic: 'Division',
            difficulty: 'Advanced',
            createdAt: new Date().toISOString(),
        },
        {
            question: 'What is 2/3 + 1/6?',
            options: JSON.stringify(['3/9', '5/6', '3/6', '4/9']),
            correctAnswer: 1,
            explanation: 'Find common denominator 6. Convert 2/3 to 4/6. Then 4/6 + 1/6 = 5/6.',
            topic: 'Fractions',
            difficulty: 'Advanced',
            createdAt: new Date().toISOString(),
        },
        {
            question: 'What is 1/2 of 3/4?',
            options: JSON.stringify(['1/4', '3/8', '2/6', '1/8']),
            correctAnswer: 1,
            explanation: 'Multiply fractions: 1/2 × 3/4 = 3/8. Multiply numerators (1 × 3 = 3) and denominators (2 × 4 = 8).',
            topic: 'Fractions',
            difficulty: 'Advanced',
            createdAt: new Date().toISOString(),
        },
        {
            question: 'What is 3.25 + 1.75?',
            options: JSON.stringify(['4.5', '5', '5.5', '6']),
            correctAnswer: 1,
            explanation: 'Add decimals by aligning decimal points: 3.25 + 1.75 = 5.00 or simply 5.',
            topic: 'Decimals',
            difficulty: 'Advanced',
            createdAt: new Date().toISOString(),
        },
        {
            question: 'What is 8.4 ÷ 2?',
            options: JSON.stringify(['3.2', '4.0', '4.2', '4.4']),
            correctAnswer: 2,
            explanation: 'Divide 8.4 by 2. Think: 8 ÷ 2 = 4, and 0.4 ÷ 2 = 0.2, so 4 + 0.2 = 4.2.',
            topic: 'Decimals',
            difficulty: 'Advanced',
            createdAt: new Date().toISOString(),
        },
    ];

    await db.insert(quizQuestions).values(sampleQuestions);
    
    console.log('✅ Quiz questions seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});